#!/bin/sh

# Generates workspaces for all monitors
python $HOME/.config/bspwm/workspaces.py &

# Launch sxhkd if not already open
pgrep -x sxhkd > /dev/null || sxhkd & # Keybinds

# Launch Programs, even when refreshed with [Code + Shift + R]
picom & # Compositor
betterlockscreen -w & # Wallpaper
nvidia-settings --config=$XDG_CONFIG_HOME/nvidia/settings --load-config-only & # Load nvidia settings
$HOME/.config/polybar/launch.sh & # Polybar
xset r rate 375 45 & # Typing repeat speed

# Launch Programs only on login, and not on refresh of bspwm
[ "$1" = 0 ] && {
  discord & # Discord
  /usr/lib/mate-polkit/polkit-mate-authentication-agent-1 & # Polkit
  $HOME/.local/scripts/xidlehook.sh & # idle lock and suspend
  /usr/bin/openrgb -p blue.orp & # RGB
  greenclip daemon & # Clipboard manager
  redshift & # Blue light filter
}

bspc config border_width        		3
bspc config window_gap          		6
bspc config normal_border_color			"#171a1f"
bspc config active_border_color			"#171a1f"
bspc config focused_border_color		"#7aa2f7"
bspc config presel_feedback_color		"#171a1f"

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer false
bspc config click_to_focus any 
bspc config pointer_follows_monitor true
