#! /bin/sh

# Generates workspaces for all monitors
python $HOME/.config/bspwm/workspaces.py &

# Launch Programs
pgrep -x sxhkd > /dev/null || sxhkd &
picom & # Compositor
nitrogen --restore & # Wallpaper

nvidia-settings --config=$XDG_CONFIG_HOME/nvidia/settings --load-config-only & # Load nvidia settings
$HOME/.config/polybar/launch.sh & # Polybar
xset r rate 375 45 & # Typing repeat speed

bspc config border_width        		3
bspc config window_gap          		6
bspc config normal_border_color			"#171a1f"
bspc config active_border_color			"#171a1f"
bspc config focused_border_color		"#171a1f"
bspc config presel_feedback_color		"#171a1f"

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer false
bspc config click_to_focus any 

# Launch Programs only on login, and not on refresh of bspwm
[ "$1" = 0 ] && {
	discord --ignore-gpu-blocklist --disable-features=UseOzonePlatform --enable-features=VaapiVideoDecoder --use-gl=desktop --enable-gpu-rasterization --enable-zero-copy --start-minimized &
	/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &
	$HOME/.local/scripts/xidlehook.sh &
	/usr/bin/openrgb -p blue.orp &
}
